import { Car } from './models';

const dealer = {
  id: 'demo-tenant',
  name: 'LAOS AUTO',
  slug: 'laos-auto',
  phone: '+8562012345678',
  whatsapp: '+8562012345678',
  messengerUrl: 'https://m.me/laosauto',
  address: 'Samsenthai Road, Vientiane Capital'
};

export const publicDemoCars: Car[] = [
  {
    id: 'demo-1',
    tenantId: dealer.id,
    tenant: dealer,
    make: 'Toyota',
    model: 'Fortuner',
    trim: '2.8L Diesel 4WD',
    year: 2024,
    priceLak: '450000000',
    mileageKm: 0,
    fuelType: 'Diesel',
    transmission: 'Auto',
    bodyType: 'SUV',
    location: 'Vientiane',
    description: 'Premium 7-seat SUV with 4WD, leather seats, navigation, backup camera, and advanced safety.',
    isFeatured: true,
    isLimitedStock: true,
    viewCount: 128,
    clickCount: 42,
    images: [{ url: 'https://image.qwenlm.ai/public_source/973aa0b4-d54d-4a42-94b0-ffca7278ae88/1909ef06b-2b07-48fb-b574-7bf05ac1480f.png', isPrimary: true }]
  },
  {
    id: 'demo-2',
    tenantId: dealer.id,
    tenant: dealer,
    make: 'Honda',
    model: 'Civic',
    trim: '1.5L Turbo CVT',
    year: 2024,
    priceLak: '280000000',
    mileageKm: 0,
    fuelType: 'Gasoline',
    transmission: 'CVT',
    bodyType: 'Sedan',
    location: 'Vientiane',
    description: 'Sport sedan with turbo engine, LED headlights, touchscreen, keyless entry, and lane assist.',
    isFeatured: true,
    isLimitedStock: false,
    viewCount: 96,
    clickCount: 35,
    images: [{ url: 'https://image.qwenlm.ai/public_source/973aa0b4-d54d-4a42-94b0-ffca7278ae88/1a42c7dc2-2892-4b68-bb6e-c1bf5c23e0a4.png', isPrimary: true }]
  },
  {
    id: 'demo-3',
    tenantId: dealer.id,
    tenant: dealer,
    make: 'Ford',
    model: 'Ranger',
    trim: '2.0L Bi-Turbo 4x4',
    year: 2024,
    priceLak: '380000000',
    mileageKm: 0,
    fuelType: 'Diesel',
    transmission: 'Auto',
    bodyType: 'Pickup',
    location: 'Vientiane',
    description: 'Work-ready pickup with 4x4, terrain management, tow package, 360 camera, and premium sound.',
    isFeatured: true,
    isLimitedStock: true,
    viewCount: 144,
    clickCount: 51,
    images: [{ url: 'https://image.qwenlm.ai/public_source/973aa0b4-d54d-4a42-94b0-ffca7278ae88/1033385a8-1441-4fd6-a643-206cacdd719e.png', isPrimary: true }]
  },
  {
    id: 'demo-4',
    tenantId: dealer.id,
    tenant: dealer,
    make: 'BYD',
    model: 'Atto 3',
    trim: 'Electric 420km Range',
    year: 2024,
    priceLak: '320000000',
    mileageKm: 0,
    fuelType: 'Electric',
    transmission: 'Auto',
    bodyType: 'EV',
    location: 'Vientiane',
    description: 'Modern EV with fast charging, panoramic roof, rotating screen, V2L output, and ADAS.',
    isFeatured: true,
    isLimitedStock: false,
    viewCount: 188,
    clickCount: 74,
    images: [{ url: 'https://image.qwenlm.ai/public_source/973aa0b4-d54d-4a42-94b0-ffca7278ae88/170af0a7a-ca4e-4484-b4ea-223d46d75016.png', isPrimary: true }]
  },
  {
    id: 'demo-5',
    tenantId: dealer.id,
    tenant: dealer,
    make: 'Mitsubishi',
    model: 'Triton',
    trim: '2.4L Diesel 4WD',
    year: 2024,
    priceLak: '350000000',
    mileageKm: 0,
    fuelType: 'Diesel',
    transmission: 'Auto',
    bodyType: 'Pickup',
    location: 'Vientiane',
    description: 'Durable pickup for Laos road conditions with Super Select 4WD and hill descent control.',
    isFeatured: false,
    isLimitedStock: false,
    viewCount: 74,
    clickCount: 18,
    images: [{ url: 'https://image.qwenlm.ai/public_source/973aa0b4-d54d-4a42-94b0-ffca7278ae88/1033385a8-1441-4fd6-a643-206cacdd719e.png', isPrimary: true }]
  },
  {
    id: 'demo-6',
    tenantId: dealer.id,
    tenant: dealer,
    make: 'Hyundai',
    model: 'Tucson',
    trim: '2.0L AWD',
    year: 2024,
    priceLak: '390000000',
    mileageKm: 0,
    fuelType: 'Gasoline',
    transmission: 'Auto',
    bodyType: 'SUV',
    location: 'Vientiane',
    description: 'Stylish SUV with panoramic sunroof, digital dash, BOSE sound, and wireless charging.',
    isFeatured: false,
    isLimitedStock: false,
    viewCount: 82,
    clickCount: 23,
    images: [{ url: 'https://image.qwenlm.ai/public_source/973aa0b4-d54d-4a42-94b0-ffca7278ae88/192f26f46-912b-4237-9714-93104bfc8474.png', isPrimary: true }]
  }
];

